fps = 12

[[token]]
name = "activity-one"
  [[token.step]]
  element = "Start"
  at_ms = 0

[[token]]
name = "activity-two"
  [[token.step]]
  element = "Start"
  at_ms = 1000

[[token]]
name = "activity-three"
  [[token.step]]
  element = "Start"
  at_ms = 2000

[[token]]
name = "activity-four"
  [[token.step]]
  element = "Start"
  at_ms = 3000
