fps = 12

[[token]]
name = "normal-payment-one"
  [[token.step]]
  element = "Start"
  at_ms = 0

[[token]]
name = "timeout-payment-one"
  [[token.step]]
  element = "Start"
  at_ms = 1500
  [[token.step]]
  element = "Boundary_Timeout"
  at_ms = 2500

[[token]]
name = "normal-payment-two"
  [[token.step]]
  element = "Start"
  at_ms = 3500

[[token]]
name = "timeout-payment-two"
  [[token.step]]
  element = "Start"
  at_ms = 5000
  [[token.step]]
  element = "Boundary_Timeout"
  at_ms = 6000

[[token]]
name = "error-payment-one"
  [[token.step]]
  element = "Start"
  at_ms = 7000
  [[token.step]]
  element = "Boundary_Timeout"
  at_ms = 8000
  [[token.step]]
  element = "Event_0v187hv"
  at_ms = 9000

[[token]]
name = "error-payment-two"
  [[token.step]]
  element = "Start"
  at_ms = 10000
  [[token.step]]
  element = "Boundary_Timeout"
  at_ms = 11000
  [[token.step]]
  element = "Event_0v187hv"
  at_ms = 12000
