name: "gh-pages"
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v26
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: datakurre
    - run: nix-shell --run "make"
    - uses: JamesIves/github-pages-deploy-action@v4.5.0
      with:
        folder: build
        clean: true
